Add several features and add MinIO
BBSRKhelp/pet_project pull request #10
Opened 2024-11-20 19:00 UTC by BBSRKhelp

Add a feature to create a pet, species, breed, photos. add MinIO to the project

2024-11-20 19:02 UTC, BBSRKhelp commented
Сначала не понял как делать 7.1 и решил начать со следующей задачи (на то время создание фичи по созданию пета), в надежде что так пойму как делать 7.1. Так получилось что сделал фичу по созданию пета и добавил minio  провайдера. Потом порядок заданий изменился и пришлось сделать еще фичу для вида и породы.

2024-11-20 19:13 UTC, BBSRKhelp commented
Вопрос 1: Как лучше назвать валидатор, хэндлер и command по созданию пета и породы.
-Пример: PetCreateCommand или PetAddCommand...
Вопрос 2: UnitOfWork нужен во всех хэндлерах где происходит сохранение в бд? обязательно там все оборачивать в try..catch..?
Вопрос 3: Добавил класс заменяющий оболочки для некоторых VO ValueObjectList, но с ним вылетал exception, связанный с тем что ef core не может сконфигурировать свойства ReadOnlyList, хотя при этом обычные оболочки также используют ReadOnlyList и все норм. Возможно уже был такой вопрос у кого то, не знаю.
Вопрос 4: Можно ли использовать логгер в Domain Layer для агрегатов и сущностей или в контроллерах?

2024-11-21 08:04 UTC, KirillSachkov requested changes

2024-11-21 08:04 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Contracts/Breed/BreedCreateRequest.cs
> +public record BreedCreateRequest(string Name)
Лучше назвать CreateBreedRequest, сначала глагол

2024-11-21 08:04 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Contracts/Pet/PetCreateRequest.cs
> +public record PetCreateRequest(
лучше сделать CreatePetRequest

2024-11-21 08:04 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Contracts/Pet/PetCreateRequest.cs
> +public record PetCreateRequest(
аналогично для всех реквестов и команд

2024-11-21 08:04 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Controllers/SpeciesController.cs
> +       [FromServices] SpeciesCreateCommandValidator commandValidator,
Команду нужно валидировать в слое с Application

2024-11-21 08:04 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Controllers/SpeciesController.cs
> +       [FromServices] SpeciesCreateCommandValidator commandValidator,
для остальных кейсов аналогично

2024-11-21 08:04 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Application/Commands/Volunteer/AddPet/PetCreateHandler.cs
> +        try
try catch нужно использовать, когда нужно сделать какие-то возвратные действи, rollback произойдет автоматически если при коммите будет ошибка

2024-11-21 08:07 UTC, KirillSachkov commented
> Вопрос 1: Как лучше назвать валидатор, хэндлер и command по созданию пета и породы. -Пример: PetCreateCommand или PetAddCommand... Вопрос 2: UnitOfWork нужен во всех хэндлерах где происходит сохранение в бд? обязательно там все оборачивать в try..catch..? Вопрос 3: Добавил класс заменяющий оболочки для некоторых VO ValueObjectList, но с ним вылетал exception, связанный с тем что ef core не может сконфигурировать свойства ReadOnlyList, хотя при этом обычные оболочки также используют ReadOnlyList и все норм. Возможно уже был такой вопрос у кого то, не знаю. Вопрос 4: Можно ли использовать логгер в Domain Layer для агрегатов и сущностей или в контроллерах?

1 и 2 вопрос в ревью написал, 3 вопрос напиши в технические вопросы в чате, там должны помочь, так сразу не скажу. 4 вопрос в домене логировать ничего не нужно, во всех остальных местах можно

2024-11-24 18:02 UTC, KirillSachkov approved these changes

2024-11-24 21:00 UTC, merged