_Добавил модель питомца и волонтера
BBSRKhelp/pet_project pull request #2
Opened 2024-08-24 17:14 UTC by BBSRKhelp

2024-08-24 17:57 UTC, Asasen1 requested changes
Commit мы пишем на английском. Мешаешь задания. Ветка B-4, а делаешь b2 и b3.

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Pets/Address.cs
> +public class Address
Address это ValueObject. У него не должно быть id и сеттеров. Так же сделай его рекордом.

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Pets/Pet.cs
> +    private Pet(string nickname, string description, string breed,string healthInformation, Address address,
Каждый параметр с новой строки.

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Pets/Pet.cs
> +    public bool Vaccinated { get; private set; }
Булевые значения должны начинаться с Is

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Pets/Pet.cs
> +    public static Result<Pet> Create(string nickname, string description, string breed,string healthInformation,
С новой строки

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Pets/Pet.cs
> +        var pet = new Pet(nickname, description, breed, healthInformation, address, weight, height,
тоже самое

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Pets/Pet.cs
> +        //...
где остальные проверки?

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Pets/Pet.cs
> +        return Result.Success(pet);
можно просто вернуть pet

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Requisites.cs
> +public class Requisites
в ед. числе

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Requisites.cs
> +    public string Titel { get; set; } = null!;
title

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Requisites.cs
> +    public string Titel { get; set; } = null!;
сеттеры убрать

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Volunteers/SocialNetwork.cs
> +public class SocialNetwork
record

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Volunteers/SocialNetwork.cs
> +    public string Title { get; set; } = null!;
сеттеры убрать

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Volunteers/Volunteer.cs
> +    public Volunteer(string fullname, string email, string description, byte workExperience, string phoneNumber, Requisites requisites)
оба конструктора приватные

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Volunteers/Volunteer.cs
> +    public Requisites Requisites { get; set; }
список реквизитов

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Volunteers/Volunteer.cs
> +    public string PhoneNumber { get; set; }
сеттеры приватные

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Volunteers/Volunteer.cs
> +    public Result<Volunteer> Create(string fullname, string email, string description, byte workExperience,
фабричный метод должен быть статическим

2024-08-24 17:57 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Volunteers/Volunteer.cs
> +        if (!email.Contains("@"))
почитай про регулярные выражения

2024-09-01 08:51 UTC, KirillSachkov approved these changes

2024-09-01 13:13 UTC, merged