_database. VO. Configurations. Id for entity
BBSRKhelp/pet_project pull request #3
Opened 2024-09-15 11:43 UTC by BBSRKhelp

_Connect the database. Create configurations for all entities. Create an entity responsible for the Id. Add a VO

2024-09-15 16:25 UTC, YaraOduvanchik requested changes

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.API/Program.cs
> +var summaries = new[]
Это удалить

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.API/Program.cs
> +app.MapGet("/weatherforecast", () =>
И это тоже удалить

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.API/Program.cs
> +record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
Удалить

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/SpeciesAggregate/Entities/Breed.cs
> +    public string BreedPet { get; }
Тут лучше назвать подругому, так как класс называется и так Breed, так что свойство не должно повторяться с названием класса, например можно Name, тогда мы свойство будем обращаться к свойству вот так: Breed.Name

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/SpeciesAggregate/Species.cs
> +    public IReadOnlyList<Breed> Breeds { get; }
Тут нужно немного исправть, мы должны добавить приватный List, чтобы мы могли добавлять породы, так как в IReadOnlyList мы неможем добавить ничего.

Должно быть вот так:
private readonly List<Breed> _breeds = [];
public IReadOnlyList<Breed> Breeds => _breeds;

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/SpeciesAggregate/Species.cs
>      public string NameOfSpecies { get; private set; }
Тут ненужно лишнее уточнение OfSpecies, и так понятно что это название Species, так как мы находимся в классе Species

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/AppearanceDetails.cs
> +    public Colour Coloration { get; }
в этом ValueObject должны быть только SpeciesId и BreedId

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/AppearanceDetails.cs
> +    public BreedId BreedId { get; }
BreedId должен быть типа Guid, так как мы неможем напрямую обратиться к породам другого аггрегата

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/Entities/Pet.cs
> +        if (appearanceDetails.SpeciesId == SpeciesId.Empty())
Не нужно проводить валидацию ValueObject, так как при создании ValueObject, мы и так его валидируем

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/Entities/Pet.cs
> +        if (appearanceDetails.BreedId == BreedId.Empty())
убрать

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/Entities/Pet.cs
> +        if (appearanceDetails.Weight <= 0 || appearanceDetails.Weight > Constants.MAX_MEDIUM_LOW_TEXT_LENGTH)
убрать

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/Entities/Pet.cs
> +        if (appearanceDetails.Height <= 0 || appearanceDetails.Height > Constants.MAX_MEDIUM_LOW_TEXT_LENGTH)
убрать

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/Entities/Pet.cs
> +        if (IsNullOrEmpty(healthDetails.HealthInformation))
убрать

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/Entities/Pet.cs
> +    public string PhoneNumber { get; private set; }
Лучше добавить отдельный ValueObject для PhoneNumber, так как такое свойство достаточно сложно валидировать (проверка на правильность ввода телефона)

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/Entities/Pet.cs
> +        if (!phoneNumber.Contains(@"^((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}$"))
Это лучше вынести в отдельный ValueObject для номера телефона

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/PetDetails.cs
> +    public List<PetPhoto>? PetPhotos { get; }
Тут лучше сделать IReadOnlyList

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/PetDetails.cs
> +    public List<Requisite> Requisites { get; }
Тут тоже

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/PetDetails.cs
> +    private PetDetails(List<PetPhoto> petPhoto, List<Requisite> requisite)
Тут лучше сделать IEnumerable вместо List

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/PetDetails.cs
> +    public static Result<PetDetails> Create(List<PetPhoto> petPhoto, List<Requisite> requisite)
Тут не нужен фабричный метод, так как валидировать нечего

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/PetPhoto.cs
> +    public string? Path { get; }
Лучше убрать '?'

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/VolunteerDetails.cs
> +    private VolunteerDetails(List<SocialNetwork> socialNetworks, List<Requisite> requisites)
Тут сделать также как я написал в PetDetails

2024-09-15 16:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Infrastructure/ApplicationDbContext.cs
> +    }
Тут можно добавить ещё:

optionsBuilder.EnableSensitiveDataLogging();

2024-09-17 06:20 UTC, BBSRKhelp commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/PetDetails.cs
> +    private PetDetails(List<PetPhoto> petPhoto, List<Requisite> requisite)
Чтобы ограничить функции добавления и удаления данных в коллекции? А если так, то полезно ли нам это? Вдруг добавиться еще одна фотография пета? Мы будем полностью сносить список и новый добавлять?

2024-09-17 11:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/Entities/Pet.cs
> +        if (appearanceDetails.SpeciesId == SpeciesId.Empty())
Не убрал это

2024-09-17 11:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/VolunteerDetails.cs
> +    public IEnumerable<SocialNetwork> SocialNetworks { get; }
У этих свойств должен быть тип IReadOnlyList.

IEnumerable должен быть у параметров в конструкторе.

2024-09-17 11:25 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/PetDetails.cs
> +    private PetDetails(List<PetPhoto> petPhoto, List<Requisite> requisite)
Я написал именно про параметры в конструкторе.
И да, нам нужно ограничить возможность какого-либо изменения коллекций, так как VO мы неможем менять, мы должны полностью заменять их на новый экземпляр

2024-09-17 11:30 UTC, YaraOduvanchik requested changes
В сущности Pet, в фабричном методе не исправил + я написал ещё коммент

2024-09-17 11:30 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/PetDetails.cs
> +    public IEnumerable<PetPhoto>? PetPhotos { get; }
У этих свойств должен быть тип IReadOnlyList.

IEnumerable должен быть у параметров в конструкторе.

Ответил на комментарий твой, там написал зачем это нужно.

2024-09-17 12:12 UTC, BBSRKhelp commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/AppearanceDetails.cs
> +    public Colour Coloration { get; }
Этот VO создать надо в SpeciesAggregate или в VolunteerAggregate?

2024-09-18 10:14 UTC, YaraOduvanchik commented on backend/src/PetFamily.Domain/VolunteerAggregate/ValueObjects/AppearanceDetails.cs
> +    public Colour Coloration { get; }
В VolunteerAggregate, так как это относится к Pet

2024-09-18 15:26 UTC, merged